CREATE TABLE IF NOT EXISTS users (
  email VARCHAR(200) NOT NULL PRIMARY KEY,
  password VARCHAR(200) NOT NULL
  phone_number VARCHAR(200) NOT NULL
  first_name VARCHAR(200) NOT NULL ,
  last_name VARCHAR(200) NOT NULL
);